version: '3.8'

networks:
  jenkins:
    external: true

services:
  db:
    image: postgres
    container_name: storeDB
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: phumlanidev
      POSTGRES_PASSWORD: Chr1st1@n9432
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - jenkins
    restart: always

volumes:
  postgres-data:

