name: test-build-package

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_DB: ${{ POSTGRES_DB }}
          POSTGRES_USER: ${{ POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ POSTGRES_PASSWORD }}

    env:
      SPRING_DATASOURCE_URL: ${{ SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ POSTGRES_USER }}
      SPRING_DATASOURCE_PASSWORD: ${{ POSTGRES_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h localhost -p 5432; do
            sleep 1
          done
          echo "PostgreSQL is ready."

      - name: Run tests
        run: mvn test --batch-mode

      - name: Build with Maven
        run: mvn clean install --batch-mode

      - name: Package application
        run: mvn package --batch-mode
